remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Luisa Cardona Torres
description: PhD student at Instituto Nacional de Astrofísica, Óptica y Electrónica (INAOE) in Puebla, México. I study the physical and morphological properties of Dusty Star-Forming Galaxies (DSFGs). 
# https://pages-themes.github.io/slate/
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-content-to-your-github-pages-site-using-jekyll#about-content-in-jekyll-sites
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# https://github.com/pages-themes/minimal
