theme: jekyll-theme-minimal
title: Luisa Cardona Torres
description: PhD student at Instituto Nacional de Astrofísica, Óptica y Electrónica (INAOE) in Puebla, México. I study the physical and morphological properties of Dusty Star-Forming Galaxies (DSFGs). 
